server:
    port: 8761
spring:
    application:
        name: eureka
    main:
        allow-bean-definition-overriding: true

eureka:
    instance:
        hostname: localhost
    client:
        fetchRegistry: false
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0


