server:
    port: 9999

spring:
    profiles:
        active: master
    application:
        name: stone
    config:
        import: optional:configserver:http://localhost:8888
        #config:
        #uri: optional:configserver:http://localhost:8888

eureka:
    instance:
        hostname: stone
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        healthcheck:
            enabled: true
management:
    endpoints:
        web:
            exposure:
                include: refresh