server:
    port: 8888

eureka:
    instance:
        hostname: config-x
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


spring:
    application:
        name: config-x
    cloud:
        config:
            server:
                git:
                    # uri: ssh://localhost/config-repo
                    uri: file:///Users/viber/Mamba/THE-WAY-TO-THE-FUTURE/spring-practice/eureka-demo/config-repo
                    clone-on-start: true
                    default-label: master
    config:
        name: config-x-server