server:
    port: 8888

spring:
    application:
        name: sql-injection
    datasource:
        url: jdbc:mysql://172.17.41.250:33306/viber
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5