spring:
    application:
        name: spring-async
    datasource:
        url: jdbc:mysql://localhost:3306/viber
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000